            Creación y Indexación:

In [1]:
import numpy as np

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [ ]:
array1 = np.random.randint(10,100,50)
array1


In [ ]:
print(array1[::5])

2.Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [ ]:
array2=np.random.randint(1,21,30)
array2

In [ ]:
print(array2[1::2])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [ ]:
array3 = np.random.rand(4,6).round(2)
array3 +1

4.Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.


In [ ]:
array4= np.random.rand(6,4)
array4


In [ ]:
print(array4[:,1])

In [ ]:
array4.round(2)

5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [ ]:
array5=np.random.randint(-50,50,30)
array5

In [ ]:
array5neg= array5[array5<0]
array5neg

In [ ]:
array5negindices=np.where(array5<0)
array5negindices

In [ ]:
array5b=array5[[array5negindices]]
array5b

6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [13]:
array_6 = np.random.rand(10).round(2)
array_6


array([0.42, 0.99, 0.46, 0.05, 0.39, 0.43, 0.28, 0.19, 0.5 , 0.96])

In [14]:
np.where(array_6 > 0.5) #No sé por qué devuelve una coma antes del último paréntesis


(array([1, 9]),)

7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [ ]:

array_1d = np.arange(1, 101)[:40]

resultado = array_1d[(array_1d % 3 == 0) & (array_1d % 4 == 0)]

print(f"Array original: {array_1d}")
print(f"Elementos divisibles por 3 y por 4: {resultado}")



8. BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [30]:
# No entiendo la parte de los 50 elementos, con esas simensiones solo salen 30 elementos :S

array_8 = np.random.randint(0,101, (2,3,5))
array_8



array([[[14,  0, 73, 58, 41],
        [55, 12, 10, 49, 89],
        [ 5, 73, 40, 56, 64]],

       [[57, 27, 37, 83, 51],
        [70,  9, 63, 22, 91],
        [65, 77, 76, 18, 45]]])

In [33]:
array_8_3en3 = np.where(array_8 % 3 == 0, 0, array_8)
array_8_3en3

array([[[14,  0, 73, 58, 41],
        [55,  0, 10, 49, 89],
        [ 5, 73, 40, 56, 64]],

       [[ 0,  0, 37, 83,  0],
        [70,  0,  0, 22, 91],
        [65, 77, 76,  0,  0]]])

                    Reshape y Transpose:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [ ]:


array_3d = np.random.randint(1, 101, size=(2, 3, 4))
print(array_3d)

# Utilizar reshape para convertirlo en un array 2D
array_2d = array_3d.reshape((2, -1))

print(array_2d)

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [16]:
array_2 = np.random.randint(1,60, (3,4,5))
array_2


array([[[47,  7, 25, 30,  5],
        [33,  9, 28, 53, 39],
        [49, 50, 18, 24,  4],
        [11,  4, 17, 48, 23]],

       [[28, 58, 51, 23,  9],
        [42, 14, 18, 18, 57],
        [20, 58, 14, 11, 57],
        [55, 53,  5, 29, 38]],

       [[46, 30, 35, 13, 16],
        [ 2, 55,  5, 17,  8],
        [ 9,  2, 40, 22, 31],
        [26, 18, 46,  6, 35]]])

In [19]:
array_reshape = np.reshape(array_2, (3,20))
array_reshape


array([[47,  7, 25, 30,  5, 33,  9, 28, 53, 39, 49, 50, 18, 24,  4, 11,
         4, 17, 48, 23],
       [28, 58, 51, 23,  9, 42, 14, 18, 18, 57, 20, 58, 14, 11, 57, 55,
        53,  5, 29, 38],
       [46, 30, 35, 13, 16,  2, 55,  5, 17,  8,  9,  2, 40, 22, 31, 26,
        18, 46,  6, 35]])

3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D

In [ ]:

array_3d = np.random.rand(4, 3, 2)
print(array_3d)
array_2d = array_3d.reshape((4, -1))
print(array_2d)


4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [24]:
array_4 = np.random.randint(1,60, (3,4,5))
array_4



array([[[11,  6, 36, 38,  5],
        [ 7, 16, 41, 46, 50],
        [ 1,  8, 13, 14, 27],
        [48, 20,  8, 49, 41]],

       [[45, 12, 56, 12, 15],
        [39,  6, 32, 29, 44],
        [55, 36,  8, 50, 52],
        [26, 57, 51, 20, 21]],

       [[34, 46, 57, 44, 12],
        [37, 59, 23, 20, 58],
        [51, 17, 38, 31, 16],
        [34,  8, 10, 51, 38]]])

In [26]:
array_transpose4 = np.transpose(array_4,(1,0,2))
array_transpose4

array([[[11,  6, 36, 38,  5],
        [45, 12, 56, 12, 15],
        [34, 46, 57, 44, 12]],

       [[ 7, 16, 41, 46, 50],
        [39,  6, 32, 29, 44],
        [37, 59, 23, 20, 58]],

       [[ 1,  8, 13, 14, 27],
        [55, 36,  8, 50, 52],
        [51, 17, 38, 31, 16]],

       [[48, 20,  8, 49, 41],
        [26, 57, 51, 20, 21],
        [34,  8, 10, 51, 38]]])

5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [ ]:

array_3d = np.random.rand(4, 3, 2)
print(array_3d)
array_transposed = np.transpose(array_3d, (1, 2, 0))
print(array_transposed)


6. ¿Qué diferencia existe entre el reshape y el transpose?

Con "reshape", siempre y cuando se respete el número de valores, cambia la forma del array. Sin embargo, con "transpose" se intercambian las dimensiones. 

7. ¿Y entre el transpose y el swapaxes?

            Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [ ]:

array_3d = np.round(np.random.rand(2, 3, 5), 1)
print(array_3d)



2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".
 a modo de ejemplo. Si tenemos el siguiente array 
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],
​
[[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]])
​
sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0
​
nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],
​
[["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]]

In [34]:
array_funcion = np.random.random_sample((2,3,5)).round(1)
array_funcion

array([[[0.9, 0. , 0.8, 0.5, 0.1],
        [0.5, 0.3, 0.4, 0.5, 0.9],
        [0.1, 0.4, 0.5, 0.8, 0.6]],

       [[0.8, 0.6, 0.3, 1. , 0.3],
        [0.3, 0.3, 0. , 1. , 1. ],
        [0.3, 0.9, 0.1, 0.9, 0.1]]])

In [37]:
array_media = np.mean(array_funcion)
print(f"La media del array es {array_media}")


La media del array es 0.5066666666666666


In [38]:
# - Si el valor del array es igual que la media, se reemplaza por "A".

np.where(array_funcion == array_media, "A", array_funcion)


array([[['0.9', '0.0', '0.8', '0.5', '0.1'],
        ['0.5', '0.3', '0.4', '0.5', '0.9'],
        ['0.1', '0.4', '0.5', '0.8', '0.6']],

       [['0.8', '0.6', '0.3', '1.0', '0.3'],
        ['0.3', '0.3', '0.0', '1.0', '1.0'],
        ['0.3', '0.9', '0.1', '0.9', '0.1']]], dtype='<U32')

In [39]:
# - Si el valor del array es mayor que la media, se reemplaza por "B"
np.where(array_funcion <  array_media, "B", array_funcion)

array([[['0.9', 'B', '0.8', 'B', 'B'],
        ['B', 'B', 'B', 'B', '0.9'],
        ['B', 'B', 'B', '0.8', '0.6']],

       [['0.8', '0.6', 'B', '1.0', 'B'],
        ['B', 'B', 'B', '1.0', '1.0'],
        ['B', '0.9', 'B', '0.9', 'B']]], dtype='<U32')

In [42]:
# - Si el valor del array es menor que la media, se reemplaza por "C"
np.where(array_funcion > array_media, "C", array_funcion)

array([[['C', '0.0', 'C', '0.5', '0.1'],
        ['0.5', '0.3', '0.4', '0.5', 'C'],
        ['0.1', '0.4', '0.5', 'C', 'C']],

       [['C', 'C', '0.3', 'C', '0.3'],
        ['0.3', '0.3', '0.0', 'C', 'C'],
        ['0.3', 'C', '0.1', 'C', '0.1']]], dtype='<U32')

In [45]:
# - Si el valor es igual que el máximo, se reemplaza por "D"
array_maximo = np.max(array_funcion)
np.where(array_funcion == array_maximo, "D", array_funcion)


array([[['0.9', '0.0', '0.8', '0.5', '0.1'],
        ['0.5', '0.3', '0.4', '0.5', '0.9'],
        ['0.1', '0.4', '0.5', '0.8', '0.6']],

       [['0.8', '0.6', '0.3', 'D', '0.3'],
        ['0.3', '0.3', '0.0', 'D', 'D'],
        ['0.3', '0.9', '0.1', '0.9', '0.1']]], dtype='<U32')

In [47]:
#Si el valor es igual que el mínimo, se reemplaza por "E"

array_minimo= np.min(array_funcion)
np.where(array_funcion == array_minimo, "E", array_funcion)


array([[['0.9', 'E', '0.8', '0.5', '0.1'],
        ['0.5', '0.3', '0.4', '0.5', '0.9'],
        ['0.1', '0.4', '0.5', '0.8', '0.6']],

       [['0.8', '0.6', '0.3', '1.0', '0.3'],
        ['0.3', '0.3', 'E', '1.0', '1.0'],
        ['0.3', '0.9', '0.1', '0.9', '0.1']]], dtype='<U32')